version: '3.9'
services:
  # Apache webserver + PHP
  webserver:
    container_name: local-apache-php-server
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 8111:80
    depends_on:
      - database  # Depends on the MySQL database service

  # MySQL Database Service
  database:
    container_name: local-mysql-bdd
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grupo14
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
    # Maps port 3306 on the host to port 3306 on the MySQL container
      - "3306:3306"
    volumes:
      - "./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
